### ISSUE TITLE
Cannot start, ModuleNotFoundError

### ISSUE THREAD

**Issue by pandalec** [Cadair/matrix-appservice-hangouts#23]
Hi! I try to startup the bridge, but it won't start with the following error:

```
Traceback (most recent call last):
  File "/root/.synapse/matrix-appservice-hangouts/bin/hangoutsas", line 11, in <module>
    load_entry_point('appservice-framework==0.1.0', 'console_scripts', 'hangoutsas')()
  File "/root/.synapse/matrix-appservice-hangouts/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.synapse/matrix-appservice-hangouts/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/root/.synapse/matrix-appservice-hangouts/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/root/.synapse/matrix-appservice-hangouts/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'appservice_framework.__main__'
```
It looks like an error from the appservice-framwork, but I isntalled it inside the venv with pip3 install -r requirements. Worked without a problem. 

`Successfully installed appservice-framework-0.1.0`

BR
par

**Comment by pandalec** [comment]
No idea? Tried it with a dockerized installation, same result. It seams like main is nowhere defined

**Comment by Cerothen** [comment]
I too am getting the exact same error. I have done some general googling and can't seem to identify the solution.

Error:
```
/opt/matrix-appservice-hangouts# hangoutsas --help
Traceback (most recent call last):
  File "/usr/local/bin/hangoutsas", line 11, in <module>
    load_entry_point('appservice-framework==0.1.0', 'console_scripts', 'hangoutsas')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'appservice_framework.__main__'
```
Python/Pip Versions
```
/opt/matrix-appservice-hangouts# pip3.6 -V
pip 18.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

/opt/matrix-appservice-hangouts# python3.6 -V
Python 3.6.4
```
Python Installed Modules:
```
/opt/matrix-appservice-hangouts# python3.6
Python 3.6.4 (default, Oct 15 2018, 21:37:20)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> help("modules")

Please wait a moment while I gather a list of all available modules...

/usr/local/lib/python3.6/site-packages/sphinx/websupport/__init__.py:25: RemovedInSphinx20Warning: sphinx.websupport module is now provided as sphinxcontrib-websupport. sphinx.websupport will be removed at Sphinx-2.0. Please use the package instead.
  RemovedInSphinx20Warning)
__future__          async_timeout       imghdr              selectors
_ast                asynchat            imp                 setup
_asyncio            asyncio             importlib           setuptools
_bisect             asyncore            inspect             shelve
_blake2             atexit              io                  shlex
_bootlocale         attr                ipaddress           shutil
_bz2                audioop             itertools           signal
_codecs             babel               jinja2              site
_codecs_cn          base64              json                six
_codecs_hk          bdb                 keyword             smtpd
_codecs_iso2022     binascii            lib2to3             smtplib
_codecs_jp          binhex              linecache           sndhdr
_codecs_kr          bisect              locale              snowballstemmer
_codecs_tw          bs4                 logging             socket
_collections        builtins            lzma                socketserver
_collections_abc    bz2                 macpath             sphinx
_compat_pickle      cProfile            macurl2path         sphinx_automodapi
_compression        calendar            mailbox             sphinxcontrib
_crypt              certifi             mailcap             spwd
_csv                cgi                 markupsafe          sqlalchemy
_ctypes             cgitb               marshal             sqlite3
_ctypes_test        chardet             math                sre_compile
_curses             chunk               matrix_appservice_hangouts sre_constants
_curses_panel       click               matrix_client       sre_parse
_datetime           cmath               mechanicalsoup      ssl
_decimal            cmd                 mimetypes           stat
_dummy_thread       code                mmap                statistics
_elementtree        codecs              modulefinder        string
_functools          codeop              msilib              stringprep
_hashlib            collections         multidict           struct
_heapq              colorsys            multiprocessing     subprocess
_imp                compileall          netrc               sunau
_io                 concurrent          nis                 symbol
_json               configargparse      nntplib             symtable
_locale             configparser        ntpath              sys
_lsprof             contextlib          nturl2path          sysconfig
_markupbase         copy                numbers             syslog
_md5                copyreg             opcode              tabnanny
_multibytecodec     crypt               operator            tarfile
_multiprocessing    csv                 optparse            telnetlib
_opcode             ctypes              os                  tempfile
_operator           curses              ossaudiodev         termios
_osx_support        datetime            packaging           test
_pickle             dbm                 parser              textwrap
_posixsubprocess    decimal             pathlib             this
_pydecimal          difflib             pdb                 threading
_pyio               dis                 pickle              time
_random             distutils           pickletools         timeit
_sha1               doctest             pip                 tkinter
_sha256             docutils            pipes               token
_sha3               dummy_threading     pkg_resources       tokenize
_sha512             easy_install        pkgutil             trace
_signal             email               platform            traceback
_sitebuiltins       encodings           plistlib            tracemalloc
_socket             ensurepip           poplib              tty
_sqlite3            enum                posix               turtle
_sre                errno               posixpath           turtledemo
_ssl                faulthandler        pprint              types
_stat               fcntl               profile             typing
_string             filecmp             pstats              unicodedata
_strptime           fileinput           pty                 unittest
_struct             fnmatch             pwd                 urllib
_symtable           formatter           py_compile          urllib3
_sysconfigdata_m_linux_x86_64-linux-gnu fractions           pyclbr              urwid
_testbuffer         ftplib              pydoc               uu
_testcapi           functools           pydoc_data          uuid
_testimportmultiple gc                  pyexpat             venv
_testmultiphase     genericpath         pygments            warnings
_thread             getopt              pyparsing           wave
_threading_local    getpass             pytz                weakref
_tkinter            gettext             queue               webbrowser
_tracemalloc        glob                quopri              wheel
_warnings           grp                 random              wsgiref
_weakref            gzip                re                  xdrlib
_weakrefset         hangups             readlike            xml
abc                 hashlib             readline            xmlrpc
aifc                heapq               reparser            xxlimited
aiohttp             hmac                reprlib             xxsubtype
alabaster           html                requests            yarl
antigravity         http                resource            zipapp
appdirs             idlelib             rlcompleter         zipfile
appservice_framework idna                runpy               zipimport
argparse            idna_ssl            sched               zlib
array               imagesize           secrets
ast                 imaplib             select
```
